stages:
  - build_and_test
  - test_wasm

jobs:
  include:
    - stage: build_and_test
      name: Build & Test
      language: rust
      before_script: cargo install wasm-pack
      script: cargo build && cargo test
      after_script: cd abra_wasm && ./build.sh
      cache: cargo
    - stage: test_wasm
      name: Test the WASM Submodule in NodeJS
      language: node_js
      before_install: cd abra_wasm/js-tests
      install: npm install
      script: npm test
