stages:
  - build_and_test
  - build_and_test_wasm

jobs:
  include:
    - stage: build_and_test
      name: Build & Test (No WASM)
      language: rust
      script:
        - cargo build
        - cargo test
      cache: cargo

    - stage: build_and_test_wasm
      name: Build & Test the WASM Submodule in NodeJS
      language: rust
      before_install:
        - nvm install stable
        - cargo install wasm-pack || echo "wasm-pack already installed"
        - cd abra_wasm
        - ./build.sh
        - cd js-tests
      install: npm install
      script: npm test
