[package]
name = "abra_core"
version = "0.1.0"
authors = ["Ken Gorab <ken.gorab@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.3.0"
strum = "0.15.0"
strum_macros = "0.15.0"

[lib]
name = "abra_core"
path = "src/lib.rs"
