[package]
name = "abra_llvm"
version = "0.1.0"
edition = "2018"

[dependencies]
abra_core = { path = "../abra_core" }
cty = "0.2.2"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm11-0"] }
itertools = "0.9.0"

[dev-dependencies]
assert_cmd = "2.0.10"
