[package]
name = "gen_native_types"
version = "0.0.1"
authors = ["Ken Gorab <ken.gorab@gmail.com>"]
edition = "2018"

[dependencies]
abra_core = { path = "../abra_core" }
heck = "0.3.1"
proc-macro2 = "1.0.20"
quote = "1.0.7"
