[package]
name = "abra"
version = "0.1.0"
authors = ["Ken Gorab <ken.gorab@gmail.com>"]
edition = "2018"

[dependencies]
abra_core = { path = "../abra_core" }
#clap = "2.33.0"
clap = { git = "https://github.com/clap-rs/clap" }
