name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'v0.9.0'
    - name: Build
      run: cargo build
    - name: Run rust tests
      run: cargo test --verbose
    - name: Run wasm tests
      run: |
        cd abra_wasm && WASM_PACK_TARGET=nodejs ./build.sh && cd ..
        cd abra_wasm/js-tests
        npm install
        npm test

