name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Install QBE
      run: |
        git clone -b fork2 --single-branch https://github.com/kengorab/qbe-mirror
        mv qbe-mirror qbe
        cd qbe
        make
    - name: Setup QBE
      run: |
        echo "PATH=$(pwd)/qbe:$PATH" >> $GITHUB_ENV
    - name: Install ext dependencies
      run: ./projects/compiler/scripts/configure-libgc.sh
    - name: Install abra
      run: |
        mkdir abra-linux
        wget https://github.com/kengorab/abra-lang/releases/latest/download/abra-linux.tar.gz
        tar -xzf abra-linux.tar.gz -C abra-linux
        echo "PATH=$(pwd)/abra-linux:$PATH" >> $GITHUB_ENV
        echo "ABRA_STD=`realpath $(pwd)/projects/std/src`" >> $GITHUB_ENV
        echo "ABRA_ROOT=`realpath $(pwd)/abra-linux`" >> $GITHUB_ENV
    - name: Run tests
      run: |
        cd projects/compiler
        node test/run-tests.js
    - name: Build abra-next
      run: |
        cd projects/cli
        abra build -o cli ./main.abra
        ./cli build -o abra-next ./main.abra
    - name: Run tests against abra-next (compiler)
      run: |
        cd projects/compiler
        ABRA_CLI=./../cli/abra-next node test/run-tests.js
    - name: Run tests against abra-next (ir-compiler)
      run: |
        cd projects/cli
        ./abra-next build -o abra-next2 ./main.abra

        cd ../compiler
        ABRA_CLI=./../cli/abra-next2 node test/run-tests.js
